//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// Ursprünglicher Dateiname:
// Erstellungsdatum: 20.01.2016 12:43:41
namespace MyApplication1.aspverbindung
{
    
    /// <summary>
    /// Im Schema sind keine Kommentare für "Container" vorhanden.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisiert ein neues Container-Objekt.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis in
        /// Visual Studio konfiguriert ist, von demjenigen unterscheidet,
        /// der im Server-Schema angegeben ist, verwenden Sie Typemapper,
        /// um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "aspserver_sfb.Models", "MyApplication1.aspverbindung");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis in
        /// Visual Studio konfiguriert ist, von demjenigen unterscheidet,
        /// der im Server-Schema angegeben ist, verwenden Sie Typemapper,
        /// um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("MyApplication1.aspverbindung", global::System.StringComparison.Ordinal))
            {
                return string.Concat("aspserver_sfb.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "Inserate" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Inserat> Inserate
        {
            get
            {
                if ((this._Inserate == null))
                {
                    this._Inserate = base.CreateQuery<Inserat>("Inserate");
                }
                return this._Inserate;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Inserat> _Inserate;
        /// <summary>
        /// Im Schema sind keine Kommentare für "Inserate" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInserate(Inserat inserat)
        {
            base.AddObject("Inserate", inserat);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = @"<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edmx""><edmx:DataServices m:DataServiceVersion=""3.0"" m:MaxDataServiceVersion=""3.0"" xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataservices/metadata""><Schema Namespace=""aspserver_sfb.Models"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityType Name=""Inserat""><Key><PropertyRef Name=""ID"" /></Key><Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" /><Property Name=""Name"" Type=""Edm.String"" /><Property Name=""Beschreibung"" Type=""Edm.String"" /><Property Name=""Bild"" Type=""Edm.Byte"" Nullable=""false"" /></EntityType></Schema><Schema Namespace=""Default"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityContainer Name=""Container"" m:IsDefaultEntityContainer=""true""><EntitySet Name=""Inserate"" EntityType=""aspserver_sfb.Models.Inserat"" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "aspserver_sfb.Models.Inserat" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Inserate")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Inserat : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues Inserat-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="bild">Anfangswert von Bild.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Inserat CreateInserat(int ID, byte bild)
        {
            Inserat inserat = new Inserat();
            inserat.ID = ID;
            inserat.Bild = bild;
            return inserat;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Beschreibung" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Beschreibung
        {
            get
            {
                return this._Beschreibung;
            }
            set
            {
                this.OnBeschreibungChanging(value);
                this._Beschreibung = value;
                this.OnBeschreibungChanged();
                this.OnPropertyChanged("Beschreibung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Beschreibung;
        partial void OnBeschreibungChanging(string value);
        partial void OnBeschreibungChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Bild" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte Bild
        {
            get
            {
                return this._Bild;
            }
            set
            {
                this.OnBildChanging(value);
                this._Bild = value;
                this.OnBildChanged();
                this.OnPropertyChanged("Bild");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _Bild;
        partial void OnBildChanging(byte value);
        partial void OnBildChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
